config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'

  get '/shipping', to: 'customers#new', as: :customer
  post '/shipping', to: 'customers#create'

  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  post '/contact-us', to: 'contacts#create'

  # Pages Controller
  get '/about', to: 'pages#about'
  get '/shipping-info', to: 'pages#tracking'
  get '/refunds', to: 'pages#refunds'
  get 'order-received', to: 'pages#finished'
end

app/models/order.rb
class Order < ApplicationRecord

	has_many :items, class_name: 'OrderItem'
	has_one :customer
	

	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def new
		@order = current_cart.order
		@items = current_cart.order.items
	end

	def create
		customer = current_cart.order.customer
		token = params[:stripeToken]
		amount = current_cart.sub_total * 100
		email = customer.email
		if amount > 0
			charge = Stripe::Charge.create({
				amount: amount.round,
				currency: 'usd',
				description: email,
				source: token,
			})
		end
		@items = current_cart.order.items
		@order = current_cart.order
		id = @order.customer.id
		if @order.update_attributes(order_params.merge(status: 'open', customer_id: id))
			session[:cart_token] = nil
			flash[:success] = "Your order was successful! Check your Email shortly for receipt and shipping inforomation."
			redirect_to order_received_path
		end
	end


	private
	def order_params
		params.require(:order).permit(:cardname)
	end
end

app/views/orders/new.html.erb
<div class="alert alert-success text-center mt-3" style="position: fixed; width: 100%; z-index: 9999;">
	Free Shipping to <%= @order.customer.country_name %>!
</div>
<!-- Jquery timer <span id="time"></span> -->

<div class="container bgcustom mb-1">
	<div class="row order-page">
		<div class="col-md-6">
			<div class="card bg-light mt-5">
				<div class="card-title text-center mt-3">
					<h5 class="text-center mb-3"> Order Summary</h5>
				</div>
	      	<% @items.each do |i| %>
	      	<li class="media mx-3">
						<%= link_to i.product do %>
							<%= image_tag i.product.image, class: 'checkout-img ml-4' %>
						<% end %>
						<div class="media-body text-right mt-4 w-75">
							<small class="text-right my-n1">
			      		<strong><%= i.quantity %></strong> x <%= i.product.title %> = 
								<%= number_to_currency i.price %>
							</small>
						</div>
					</li>
					<% end %>
					<hr class="my-3"/>
					<ul class="list-unstyled mt-n2 mr-3"><small class="text-muted">
						<li class="text-right">Sub Total: <%=number_to_currency current_cart.sub_total %></li>
						<li class="text-right">Tax: $0.00</li>
						<li class="text-right">Shipping: <strike>$5.99</strike>*</li>
						<li class="text-right">*Est. shipping time 1-4 weeks</li></small>
						<li class="text-right">Total: <strong>US <%=number_to_currency current_cart.sub_total %></strong></li>
					</ul>
				</div>
			</div>
			<div class="col-md-6">
				<div class="card bg-light my-2">
					<div class="card-title text-center mt-3">
						<h5> Payment Information </h5>
					</div>
					<div class="card-body mt-n2">
						<ul class="list-unstyled mx-4 bg-white mb-1"><small>
							<li><%= @order.customer.firstname %> <%= @order.customer.lastname %></li>
							<li><%= @order.customer.address %> <%= @order.customer.optional %></li>
							<li><%= @order.customer.city %> <%= @order.customer.state %> <%= @order.customer.zip %></li></small>
						</ul>
						<u class="mx-3 mt-n4"><small><%= link_to "Not right?", customer_path %></u>
						
					<%= form_for @order, url: checkout_path, html: { id: 'checkoutForm'} do |f| %>
					<%= hidden_field_tag :customer_id, :value => params[:customer_id] %>
		        <div class="mx-2 mb-4 mt-3">	
		        	<div class="field form-group">
		        		<%= label_tag "Name on Card" %>
								<%= f.text_field :cardname, class: 'form-control', placeholder: 'First & Last Name', required: true, autofocus: true %>
							</div>				
							<div class="field form-group">
		            <%= label_tag "Card Number" %>
		            <div id="card-element" class="form-control"></div>
		            <div id="card-errors" role="alert"></div>
		          </div></small>
		      </div>
		      <div class="mx-3 mb-3">
		 				<%= f.submit "Pay #{number_to_currency current_cart.sub_total}", class: 'btn btn-block text-center btn-custom text-white', id: 'submitBtn', :data => {disable_with: false} %>
	 				</div>	 				
					<% end %>
	 				<div class="row text-center mt-4">
	 					<div class="col">
	 						<%= image_tag 'https://believebamboo.s3-us-west-1.amazonaws.com/badge1.png', class: 'w-75' %>
 						</div>
	 					<div class="col">
		 					<%= image_tag 'https://believebamboo.s3-us-west-1.amazonaws.com/badge2.png', class: 'w-75' %>
		 				</div>
		 				<div class="col">
		 					<%= image_tag 'https://believebamboo.s3-us-west-1.amazonaws.com/badge3.png', class: 'w-75 mt-n2' %>
		 				</div>
 						<div class="col">
		 					<%= image_tag 'https://believebamboo.s3-us-west-1.amazonaws.com/badge5.png', class: 'w-100' %>
		 				</div>
		 			</div>
	 			</div>
	 		</div>
    </div>
  </div>
</div>
