config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'

  get '/shipping', to: 'customers#new', as: :customer
  post '/shipping', to: 'customers#create'

  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  post '/contact-us', to: 'contacts#create'

  # Pages Controller
  get '/about', to: 'pages#about'
  get '/shipping-info', to: 'pages#tracking'
  get '/refunds', to: 'pages#refunds'
  get 'order-received', to: 'pages#finished'
end

app/models/contact.rb
class Contact < ApplicationRecord
  # Contact form validations
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  # GET request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new

    @order = current_cart.order
    @items = current_cart.order.items
  end 
  
  # POST request /contacts
  def create
    # Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    # Save the Contact object to the database
    if @contact.save
      # Store form fields via parameters, into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Plug variables into Contact Mailer 
      # email method and send email
      ContactMailer.contact_email(name, email, body).deliver
      # Store success message in flash hash
      # and redirect to the new action
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      # If Contact object doesn't save,
      # store errors in flash hash,
      # and redirect to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end  
  
  private
    # To collect data from form, we need to use
    # strong parameters and whitelist the form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/views/contacts/new.html.erb
<div class="container mt-4">
	<h1 class="bamboo-title text-center">Contact Us</h1>
	<h6 class="mt-n1 text-center mb-3">Questions? Suggestions? We'd like to hear from you!</h6>
	<div class="row">
		<div class="col-md-4 offset-md-4">
			<div class="card bgcustom text-white mb-5">
				<div class="card-body">
	        <%= form_for @contact, url: contact_us_path do |f| %>
	        
	          <div class="form-group">
	            <%= f.label :name %>
	            <%= f.text_field :name, class: 'form-control' %>
	          </div>    

	          <div class="form-group">
	            <%= f.label :email %>
	            <%= f.text_field :email, class: 'form-control' %>
	          </div>

	          <div class="form-group">
	            <%= f.label :comments %>
	            <%= f.text_area :comments, class: 'form-control' %>
	          </div>

	          <%= f.submit 'Submit', class: 'btn btn-success btn-block border-white' %>
	        <% end %>
      	</div>
			</div>
		</div>
	</div>
</div>