config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'

  get '/shipping', to: 'customers#new', as: :customer
  post '/shipping', to: 'customers#create'

  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  post '/contact-us', to: 'contacts#create'

  # Pages Controller
  get '/about', to: 'pages#about'
  get '/shipping-info', to: 'pages#tracking'
  get '/refunds', to: 'pages#refunds'
  get 'order-received', to: 'pages#finished'
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :reviews
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all

		@order = current_cart.order
		@items = current_cart.order.items
	end

	def show
		@product = Product.find(params[:id])
		if @product.reviews.blank?
			@avg_rating = 0
		else 
			@avg_rating = @product.reviews.average(:stars).round(2)
		end

		@order = current_cart.order
		@items = current_cart.order.items
	end
end

app/views/products/index.html.erb
 
  <header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url('https://believebamboo.s3-us-west-1.amazonaws.com/seaturtle.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h2>Believe Bamboo</h2>
            <p>100% organic BPA-free natural bamboo products</p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('https://believebamboo.s3-us-west-1.amazonaws.com/bamboo-forest2.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h3>Bamboo is the future</h3>
            <p>The fastest growing resource in the world.  It's time we take advantage of this gift from mother nature.</p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <!-- Image by Jasmin Sessler from Pixabay -->
        <div class="carousel-item" style="background-image: url('https://believebamboo.s3-us-west-1.amazonaws.com/TRASH-1900X1080.jpg')">
          <div class="carousel-caption d-none d-md-block">
            <h3>This is our beach every morning</h3>
            <p>Plastic takes 500 years to decompose.  Every single piece of plastic still exists.</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </header>

  <!-- Page Content -->
  <div class="container mt-4" id="products">

   

    <!-- Product Section -->

    <div class="row text-center">
      <% @products.each do |p| %>
      <div class="col product-item">
        <div class="card h-100 border-0">
          <%= image_tag p.image, class: 'card-img-top' %>
          <div class="card-body mt-n3">
            <h4 class="card-title text-center">
              <small class="text-danger"><strike> <%= p.price2 %> </strike></small><br/>
              <%= link_to "$#{p.price.round}", p, class: 'text-decoration-none text-dark stretched-link' %>
            </h4>
            <p class="card-text text-center"><strong><%= p.title %></strong></p>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <!-- /.row -->
  </div>

  <!-- Features Section -->

  <div class="bgcustom">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 text-white">
          <h1>Did you know?</h1>
          <ul>
            <li>Bamboo is the <strong>fastest</strong> growing plant in the world!</li>
            <li>Bamboo is not actually a tree, it's a type of grass</li>
            <li>It can grow up to a meter a day, you can literally watch it grow!</li>
            <li>Unlike trees, bamboo regrows after being harvested</li>
            <li>An adult bamboo tree can be harvested every single year making it the perfect renewable resource alternative to plastic!</li>
          </ul>
          <p>The Believe Bamboo movement was started by a group of surfers from Southern California that got fed up with the amount of plastics found in the ocean and washed ashore.</p>
        </div>
        <div class="col-lg-6 mt-3 text-center">
          <img class="img-fluid rounded custom-img" src="https://i.imgur.com/TlgUROh.gif" alt="">
        </div>
      </div>
      <!-- /.row -->
    <hr>
    </div>
  </div>
  <!-- /.container -->
  <div class="container">

    <!-- Call to Action Section -->
    <div class="row mb-4">
      <div class="col-md-6">
        <h6 class="mt-2 mb-3">Subscribe to our mailing list and find out how you can get involved in the fight against plastics!</h6>
      </div>
      <div class="col-md-6 mt-2 text-center">
        <form class="form-inline">
          <div class="form-group mx-sm-3 mb-2">
            <input type="text" class="form-control" id="emailList" placeholder="John@example.com">
          </div>
          <button type="submit" class="btn btn-custom mb-2 text-white ml-2">Subscribe</button>
      </form>
      </div>
    </div>
  </div>
    <!-- /.container -->




 

app/views/products/show.html.erb

<div class="container">
	<div class="row my-5">
		<div class="col-md-6 mb-4">
 
 <!--Carousel Wrapper-->
    <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
      <!--Slides-->
      <div class="carousel-inner text-center" role="listbox">
        <div class="carousel-item active">
        	<%= image_tag @product.image %>
        </div>
        <div class="carousel-item">
        	<%= image_tag @product.image2 %>
        </div>
        <div class="carousel-item">
          <%= image_tag @product.image3 %>
        </div>
        <div class="carousel-item">
          <%= image_tag @product.image4 %>
        </div>
        <div class="carousel-item">
          <%= image_tag @product.image5 %>
        </div>
      </div>
      <!--/.Slides-->
      <!--Controls-->
      <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
      <!--/.Controls & Thumbnails -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-thumb" data-slide-to="0" class="active mx-3">
        	<%= image_tag @product.image, class: 'd-block show-thumb' %>
        </li>
        <li data-target="#carousel-thumb" data-slide-to="1" class="mx-3">
        	<%= image_tag @product.image2, class: 'd-block show-thumb' %>
				</li>
        <li data-target="#carousel-thumb" data-slide-to="2" class="mx-3">
          <%= image_tag @product.image3, class: 'd-block show-thumb' %>
        </li>
        <li data-target="#carousel-thumb" data-slide-to="3" class="mx-3">
          <%= image_tag @product.image4, class: 'd-block show-thumb' %>
        </li>
        <li data-target="#carousel-thumb" data-slide-to="4" class="mx-3">
          <%= image_tag @product.image5, class: 'd-block show-thumb' %>
        </li>
      </ol>
    </div>
    <!--/.Carousel Wrapper-->

		</div>
		<div class="col">
			<h2><%= @product.title %></h2>
			<%= form_tag order_items_path do %>
				<%= hidden_field_tag :product_id, @product.id %>
				<div class="ml-3 my-4">
					<strong><strike class="text-danger mr-1">
            <%= @product.price2 %></strike>
            $<%= @product.price.round %></strong>
            <div class="row">
              <div class="star-rating" data-score= <%= @avg_rating %> ></div>            
               <strong class="color-custom ml-2"> ( <%= @product.reviews.count %> )</strong>
            </div>
				</div><hr/>
				<div class="row mt-5">
					<div class="col-md-3">
						<%= select_tag :quantity, options_for_select(1..5), class: 'form-control mb-2' %>
					</div>
					<div class="col">
						<%= submit_tag 'Add to Cart', class: 'btn btn-custom btn-block text-white' %>
					</div>
				</div>
        <small><p class="text-muted">Powered by Stripe secure checkout all prices are in USD</p></small>
        <div class="row mt-4 mb-n4 text-center">
          <div class="col">
            <i class="fa fa-cc-stripe fa-lg"></i>
          </div>
          <div class="col">
            <i class="fa fa-cc-visa fa-lg"></i>
          </div>
          <div class="col">
            <i class="fa fa-cc-mastercard fa-lg"></i>
          </div>
          <div class="col">
            <i class="fa fa-cc-discover fa-lg"></i>
          </div>
          <div class="col">
            <i class="fa fa-cc-amex fa-lg"></i>
          </div>
        </div>
			<% end %>

      <!-- Begin card with nav tabs -->
			<div class="card mt-5">
        <div class="card-header">
          <ul class="nav nav-pills card-header-pills row">
            <li class="nav-item col mx-n2 text-center">
              <a class="nav-link active" id="description-tab" data-toggle="tab" href="#description" role="tab" aria-controls="description" aria-selected="true">Description</a>
            </li>
            <li class="nav-item col mx-n3 text-center">
              <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="reviews" aria-selected="true">Reviews</a>
            </li>
            <li class="nav-item col mx-n2 text-center">
              <a class="nav-link" id="specs-tab" data-toggle="tab" href="#specs" role="tab" aria-controls="specs" aria-selected="true"> Specs </a>
            </li>
          </ul>
        </div>
        <div class="card-body">
          <div class="tab-content" id="myTabContent">
          <!-- Description tab -->
            <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab"><small>
              <p><%= @product.description %></p>
              <p><%= @product.description2 %></p>
              <p class="mt-2">Bamboo-<b>kun</b> is the name for the antimicrobial/antifungal bio-agent found in bamboo.  It's bamboo's natural defense against 
              harmful pests.  It is the reason why bamboo cultivation does not require any pesticides.  This makes bamboo the perfect natural replacement
              for single use plastics.  Bamboo also produces 35% more oxygen than plants of similar size, while at the same time requiring far less water!</p></small>
            </div>
          <!-- Reviews tab -->
            <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
              <ul id="reviewz">
              <% @product.reviews.each do |p| %>
                <li class="media">
                  <% if p.avatar.blank? %>
                    <%= image_tag p.image_url, class: 'review-avatar mr-3 align-self-center rounded' %>
                  <% else %>
                    <%= image_tag p.avatar, class: 'review-avatar mr-3 align-self-center rounded' %>
                  <% end %>
                  <small>
                    <div class="media-body">
                      <h6 class="d-inline mr-3"><%= p.name %></h6>                    
                      <div class="star-rating" data-score= <%= p.stars %> ></div>
                      <p class="text-muted">Country: <%= p.country %></p>                    
                      <p><%= p.comments %></p>
                    </div>
                  </small>
                </li><hr/>
                <% end %>
              </ul>
              <%= link_to "Write a Review", new_product_review_path(@product), class: 'btn btn-link' %>
            </div>
          <!-- Specs tab -->
            <div class="tab-pane fade" id="specs" role="tabpanel" aria-labelledby="specs-tab">
              <small><h6>Product material:</h6> 
              <p class="mt-n2">100% organic bpa-free natural bamboo</p>
              <h6>Product dimensions: </h6> 
              <ul class="mt-n2">
                <li><%= @product.spec1 %></li>
                <li><%= @product.spec2 %></li>
                <li><%= @product.spec3 %></li>
              </ul>
              <h6>Product SKU: </h6>
              <p class="mt-n2"># <%= SecureRandom.hex(8) %></p></small>
            </div>
          </div>
				</div>
			</div>
      <!-- /card -->
		</div>
	</div>
</div>




<script>
  $('.star-rating').raty({
    path: 'https://natesyelpdemo.s3-us-west-1.amazonaws.com/stars/',
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    }
  });
</script>