config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
  resources :products, only: [:index, :show] do
    resources :reviews, only: [:new, :create]
  end

  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', as: :checkout
  patch '/cart/checkout', to: 'orders#create'

  get '/shipping', to: 'customers#new', as: :customer
  post '/shipping', to: 'customers#create'

  get 'contact-us', to: 'contacts#new', as: 'new_contact'
  post '/contact-us', to: 'contacts#create'

  # Pages Controller
  get '/about', to: 'pages#about'
  get '/shipping-info', to: 'pages#tracking'
  get '/refunds', to: 'pages#refunds'
  get 'order-received', to: 'pages#finished'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BelieveBamboo</title>
    <link rel="shortcut icon" type="image/x-icon" href="https://believebamboo.s3-us-west-1.amazonaws.com/bblogo2.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>    
    <%= javascript_include_tag "https://js.stripe.com/v3/", type: 'text/javascript' %>

 



  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark">
      <div class="container-fluid">
        <button class="navbar-toggler mr-n2" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <%= link_to 'BelieveBamboo', root_path, class: 'navbar-brand bamboo my-n2' %>
          <!-- Font provided by 
          www.animationistgirl.bravarianpawstudios.com
          www.dreamwolvie.deviantart.com
          http://www.fontspace.com/profile/AnimationistGirl         
          -->
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto mr-5">
            <li class="nav-item">
              <%= link_to 'About', about_path, class: 'nav-link' %>
            </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownProducts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Products
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                  <% @productz.each do |p| %>
                    <%= link_to "#{p.title}", p, class: 'dropdown-item' %>
                  <% end %>
                </div>
              </li>
            <li class="nav-item">
              <%= link_to 'Contact', new_contact_path, class: 'nav-link' %>
            </li>            
            <li class="nav-item">
              <%= link_to 'Shipping', shipping_info_path, class: 'nav-link' %>
            </li>            
            <li class="nav-item">
              <%= link_to 'Refunds', refunds_path, class: 'nav-link' %>
            </li>                        
          </ul>
        </div>
        <div class="navbar-brand my-n2">
          <button class="btn btn-lg btn-custom text-white mx-n4" data-toggle="modal" data-target="#modalCart">
            <i class="fa fa-shopping-cart fa-lg"></i>
            (<%= current_cart.items_count %>)
          </button>
        </div>
      </div>
    </nav>
    <div class="mt-2 mb-n3">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type} text-center" %>
      <% end %>
    </div>
    
    <%= yield %>

    <!-- Footer -->
    <footer class="py-4 bgcustom">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; BelieveBamboo 2020</p>
      </div>
    </footer>

    <!-- Modal: modalCart -->
    <div class="modal fade" id="modalCart" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <!--Header-->
          <div class="modal-header">
            <h4 class="modal-title" id="myModalLabel">Your Cart</h4>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <!--Body-->
          <div class="modal-body">
          <ul class="list-unstyled">
            <% @items.each do |i| %>
              <li class="media mx-3">
                <%= link_to i.product do %>
                  <%= image_tag i.product.image, class: 'cart-modal-img mr-3' %>
                <% end %>
                <div class="media-body text-right mt-4 w-75">
                  <p><small><%= i.product.title %>
                  <% number_to_currency i.price %> x <%= i.quantity %> = <%= number_to_currency (i.price * i.quantity) %></small></p>
                </div>
              </li><hr/>
            <% end %>
            <% if current_cart.items_count > 0 %>
              <div class="row">
                <div class="col">
                  <ul class="list-unstyled">
                    <li class="text-right">Sub Total: <%=number_to_currency current_cart.sub_total %></li>
                  </ul>
                </div>
              </div>
              <div class="text-right">
                <%= link_to 'View Cart', cart_path, class: 'btn btn-link mt-3 mr-3' %>
                <%= link_to 'Proceed to Checkout', customer_path, class: 'btn btn-custom text-white border mt-3' %>
              </div>
            <% else %>
              <h1 class="my-5">Oops! Looks like your cart is empty... Browse our products   
              <a class="cart-link ml-2" href="/#products"><u>HERE</u></a></h1>
            <% end %>
            </div>
          </ul>
          </div>
        </div>
      </div>
    </div>
    <!-- Modal: modalCart -->
  </body>
</html>